src/marks_and_results/urls.py
from django.urls import path

from .views import *

app_name = "marks_and_results"

urlpatterns = [
    path('marks/', students_marks, name="students_marks"),
    path('add_marks/', add_marks, name="add_marks"),
    path('add_marks/entering/', marks_entering, name="marks_entering"),
    path('add_marks/marks_saving/', marks_saving, name="marks_saving"),
    path('edit_mark/<str:pk>/', edit_mark, name="edit_mark"),
    path('results/', results, name="results"),

    path('module_dropdown/', module_dropdown, name="module_dropdown"),
    path('lesson_dropdown/', lesson_dropdown, name="lesson_dropdown"),
    path('semester_dropdown/', semester_dropdown, name="semester_dropdown"),
]

src/sg_note/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views

from .views import index, edit_now_academic_year

urlpatterns = [
    path('', index, name='index'),
    path('edit_now_academic_year', edit_now_academic_year, name='edit_now_academic_year'),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('departs_and_mod/', include('departements_and_modules.urls')),
    path('marks_and_results/', include('marks_and_results.urls')),
    path('admin/', admin.site.urls),
]

src/students/urls.py
from django.urls import path

from .views import *

app_name = "students"

urlpatterns = [
    path('list/', students_list, name="students_list"),
    path('details/<str:pk>/', students_details, name="students_details"),
    path('create/', student_create_view, name="student_create"),
    path('edit/<str:pk>/', student_edit, name="student_edit"),

    path('specialities_dropdown/', specialities_dropdown, name="specialities_dropdown"),
    path('level_dropdown/', level_dropdown, name="level_dropdown"),
]

src/marks_and_results/models.py
from django.db import models

# Create your models here.
from departements_and_modules.models import Lesson, Semester, AcademicYear
from students.models import Student


class Mark(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    mark_type = models.FloatField(verbose_name="Note")
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, verbose_name="Semestre", null=True)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True)
    is_exam = models.BooleanField(null=True, default=False, verbose_name="Cochez si cela est une note d'examen")

    def __str__(self):
        return f"{self.mark_type}"

    class Meta:
        verbose_name = "note"

src/students/models.py
from datetime import datetime

import django
from django.db import models

from departements_and_modules.models import Faculty, Speciality, Lesson, Module
from systems_and_levels.models import Level, System


class Student(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Facultée")
    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, null=True, blank=True,
                                   verbose_name="Spécialitée")
    actual_level = models.ForeignKey(Level, on_delete=models.SET_NULL, blank=True, null=True,
                                     verbose_name="Niveau actuel")
    matricule = models.CharField(max_length=255, primary_key=True, unique=True, verbose_name="Matricule")
    first_name = models.CharField(max_length=150, verbose_name="Prénom")
    last_name = models.CharField(max_length=150, verbose_name="Nom")
    gender = models.CharField(max_length=20, verbose_name="Genre", null=True)
    birth = models.DateField(verbose_name="Naissance", blank=True, null=True)

    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Systeme")

    class Meta:
        verbose_name = "étudiant"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    @property
    def full_name(self):
        return f"{self.last_name} {self.first_name}"

    def _get_marks(self, lesson=None, semester=None, academic_year=None, exclude_exam=False):
        marks = self.mark_set.all()
        if lesson:
            marks = marks.filter(lesson=lesson)
        if academic_year:
            marks = marks.filter(academic_year=academic_year)
        if semester:
            marks = marks.filter(semester=semester)
        if exclude_exam:
            marks = marks.filter(is_exam=False)
        return marks

    def _get_a_lesson_class_mean(self, lesson, semester):
        """ get student marks mean in a specific lesson and return it """

        mean = None
        marks = self._get_marks(lesson=lesson, semester=semester, exclude_exam=True)
        if marks:
            marks_total = 0
            for mark in marks:
                marks_total += float(mark.mark_type)
            mean = marks_total/len(marks)
        return mean

    def _get_a_lesson_exam_mark(self, lesson, semester, to_float=False):
        """ get student exam mark in a specific lesson and return it """

        exam_mark = None
        marks = self._get_marks(lesson=lesson, semester=semester)
        if marks:
            exam_mark = marks.get(is_exam=True) if marks.filter(is_exam=True) else None
            if exam_mark is not None and to_float:
                exam_mark = float(exam_mark.mark_type)
        return exam_mark

    def _get_a_lesson_semester_mean(self, lesson, semester):
        semester_mean = None
        class_mean = self._get_a_lesson_class_mean(lesson=lesson, semester=semester)
        if class_mean is not None:
            exam_mark = self._get_a_lesson_exam_mark(to_float=True, lesson=lesson, semester=semester)
            if exam_mark is not None:
                semester_mean = (class_mean * 40 + exam_mark * 60) / 100
        return semester_mean

    def _get_semester_mean(self, semester):
        get_semester_mean = None

        # modules = Module.objects.filter(semester=semester)
        # lessons = []
        # for module in modules:
        #     lessons.append(Lesson.objects.filter(module=module))
        #
        # lesson_semester_means = []
        # if lessons:
        #     for lesson in lessons:
        #         lesson_semester_mean = self._get_a_lesson_semester_mean(lesson, semester)
        #         lesson_semester_means.append(lesson_semester_mean)
        #     if lesson_semester_means:
        #         total = sum(lesson_semester_means)
        #         get_semester_mean = total/len(lesson_semester_means)
        return get_semester_mean

    def _get_annual_mean(self, academic_year):
        return None

    def get_marks(self, lesson=None, semester=None, academic_year=None):
        return self._get_marks(lesson=lesson, semester=semester, academic_year=academic_year)

    def get_a_lesson_class_mean(self, lesson, semester):
        return self._get_a_lesson_class_mean(lesson, semester)

    def get_a_lesson_exam_mark(self, lesson, semester):
        return self._get_a_lesson_exam_mark(lesson=lesson, semester=semester)

    def get_a_lesson_semester_mean(self, lesson, semester):
        return self._get_a_lesson_semester_mean(lesson, semester)

    def get_semester_mean(self, semester):
        return self._get_semester_mean(semester)

    def get_annual_mean(self, academic_year):
        return self._get_annual_mean(academic_year)

src/marks_and_results/forms.py
from django import forms
from dynamic_forms import DynamicFormMixin, DynamicField

from departements_and_modules.models import Module, Lesson, Faculty, Semester, AcademicYear


class SearchMarks(DynamicFormMixin, forms.Form):

    def get_modules(self):
        return Module.objects.filter(faculty=self["faculty"].value())

    def get_lessons(self):
        return Lesson.objects.filter(module=self["module"].value())

    def get_semesters(self):
        return Semester.objects.filter(academic_year=self["academic_year"].value())

    faculty = forms.ModelChoiceField(
        queryset=Faculty.objects.all(),
    )

    module = DynamicField(
        forms.ModelChoiceField,
        queryset=get_modules,
    )

    lesson = DynamicField(
        forms.ModelChoiceField,
        queryset=get_lessons,
    )

    academic_year = forms.ModelChoiceField(
        queryset=AcademicYear.objects.all(),
    )

    semester = DynamicField(
        forms.ModelChoiceField,
        queryset=get_semesters,
    )


class MarkCreaterForm(DynamicFormMixin, forms.Form):
    def get_modules(self):
        return Module.objects.filter(faculty=self["faculty"].value())

    def get_lessons(self):
        return Lesson.objects.filter(module=self["module"].value())

    def get_semesters(self):
        return Semester.objects.filter(academic_year=self["academic_year"].value())

    is_exam = forms.BooleanField(label="Cochez si cela est une note d'examen", required=False)

    faculty = forms.ModelChoiceField(
        queryset=Faculty.objects.all(),
    )
    module = DynamicField(
        forms.ModelChoiceField,
        queryset=get_modules,
    )

    lesson = DynamicField(
        forms.ModelChoiceField,
        queryset=get_lessons,
    )

    academic_year = forms.ModelChoiceField(
        queryset=AcademicYear.objects.all(),
    )

    semester = DynamicField(
        forms.ModelChoiceField,
        queryset=get_semesters,
    )

src/students/forms.py
from django import forms
from dynamic_forms import DynamicField, DynamicFormMixin

from systems_and_levels.models import System
from .models import *


class StudentCreateForm(DynamicFormMixin, forms.Form):
    genders = (
        ("m", "Maxcuclin"),
        ("f", "Feminin")
    )

    def get_speciality(self):
        return Speciality.objects.filter(faculty=self["faculty"].value())

    def get_level(self):
        return Level.objects.filter(system=self["system"].value())

    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(), label="Faculté")
    speciality = DynamicField(forms.ModelChoiceField, queryset=get_speciality, label="Spécialité")
    system = forms.ModelChoiceField(queryset=System.objects.all(), label="Système")
    level = DynamicField(
        forms.ModelChoiceField,
        queryset=get_level,
        label="Niveau",
    )
    matricule = forms.CharField(max_length=255, required=True, label="Matricule")
    first_name = forms.CharField(max_length=150, required=True, label="Prénom")
    last_name = forms.CharField(max_length=150, required=True, label="Nom")
    gender = forms.ChoiceField(choices=genders, required=True, label="Genre")
    birth = forms.DateField(
        widget=forms.widgets.NumberInput(attrs={"type": "date"}),
        required=False,
        label="Naissance",
    )

src/students/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from pprint import pprint

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

import students
from departements_and_modules.models import Module, Lesson, AcademicYear, Semester
from marks_and_results.models import Mark
from .forms import *
from .models import *


@login_required()
def students_list(request):
    context = {
        "students": None,

        "all_faculties": Faculty.objects.all(),
        "faculty_selected": None,
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True),
    }
    all_students = Student.objects.all()
    faculty_selected = None

    if request.method == "POST":
        # edit faculty selected in session
        request.session["students_list__faculty_selected"] = request.POST.get("faculty")

    if request.session.get("students_list__faculty_selected"):
        if request.session.get("students_list__faculty_selected") != "__all__":
            faculty_selected = get_object_or_404(Faculty, pk=request.session.get("students_list__faculty_selected"))
            all_students = all_students.filter(faculty=faculty_selected)

    context["students"] = all_students
    context["faculty_selected"] = faculty_selected
    return render(request, "students/list.html", context=context)


@login_required()
def students_details(request, pk):
    context = {
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True),
    }

    student = get_object_or_404(Student, pk=pk)

    # all
    academic_years = AcademicYear.objects.all()
    semesters = Semester.objects.all()

    # get request data
    if request.GET:
        request.session["academic_year_selected"] = request.GET.get("academic_year")
        request.session["semester_selected"] = request.GET.get("semester")

    # get academic_year
    ac_pk = request.session.get("academic_year_selected", None)
    academic_year_selected = get_object_or_404(AcademicYear, pk=ac_pk) if ac_pk else None
    if not academic_year_selected:
        academic_year_selected = academic_years.last()
    semesters = semesters.filter(academic_year=academic_year_selected)

    # get semester
    sem_pk = request.session.get("semester_selected", None)
    semester_selected = get_object_or_404(Semester, pk=sem_pk) if sem_pk else None
    if not semester_selected:
        semester_selected = semesters.last()

    student_faculty_modules = student.faculty.module_set.all()
    student_lessons = []
    for module in student_faculty_modules:
        lessons = Lesson.objects.filter(module=module)
        student_lessons.extend(lessons)

    student_marks = Mark.objects.order_by("is_exam").filter(
        student=student,
        academic_year=academic_year_selected,
        semester=semester_selected,
    )

    student_marks_mapped_lessons = []
    for lesson in student_lessons:
        marks_mapped_lesson = (lesson, [m for m in student_marks.filter(lesson=lesson)])
        student_marks_mapped_lessons.append(marks_mapped_lesson)

    marks_len = []
    for mark in student_marks_mapped_lessons:
        marks_len.append(len(mark[1]))
    max_len = max(marks_len)

    context["student"] = student
    context["student_marks"] = student_marks_mapped_lessons
    context["academic_years"] = academic_years
    context["semesters"] = semesters
    context["academic_year_selected"] = academic_year_selected
    context["semester_selected"] = semester_selected
    context["max_len"] = max_len

    return render(request, "students/students_details.html", context=context)


# created views
@login_required()
def student_create_view(request):
    context = {}

    if request.method == "POST":
        form = StudentCreateForm(request.POST)
        if form.is_valid():
            student_data = form.cleaned_data
            student = Student()

            student.faculty = student_data["faculty"]
            student.speciality = student_data["speciality"]
            student.matricule = student_data["matricule"]
            student.first_name = student_data["first_name"]
            student.last_name = student_data["last_name"]
            student.birth = student_data["birth"]
            student.actual_level = student_data["level"]
            student.system = student_data["system"]

            student.save()
            return redirect("students:students_list")
    else:
        form = StudentCreateForm()

    context["form"] = form
    return render(request, "students/student_create.html", context=context)


@login_required()
def student_edit(request, pk):
    context = {}
    student = get_object_or_404(Student, pk=pk)

    if request.method == "POST":
        form = StudentCreateForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

            student.faculty = data.get("faculty")
            student.speciality = data.get("speciality")
            student.actual_level = data.get("level")
            student.matricule = data.get("matricule")
            student.first_name = data.get("first_name")
            student.last_name = data.get("last_name")
            student.gender = data.get("gender")
            student.birth = data.get("birth")
            student.system = data.get("system")

            student.save()
            return redirect("students:students_list")
    else:
        initial = {
            "faculty": student.faculty,
            "speciality": student.speciality,
            "level": student.actual_level,
            "system": student.actual_level.system if student.actual_level else None,
            "matricule": student.matricule,
            "first_name": student.first_name,
            "last_name": student.last_name,
            "gender": student.gender,
            "birth": student.birth
        }
        form = StudentCreateForm(initial=initial)

    context["form"] = form
    context["student"] = student
    return render(request, "students/student_edit.html", context=context)


@login_required()
def specialities_dropdown(request):
    if request.GET["faculty"]:
        form = StudentCreateForm(request.GET)
        return HttpResponse(form["speciality"])
    return HttpResponse('<option value="" selected>---------</option>')


@login_required()
def level_dropdown(request):
    if request.GET["system"]:
        form = StudentCreateForm(request.GET)
        return HttpResponse(form["level"])
    return HttpResponse('<option value="" selected>---------</option>')

src/students/templates/students/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/list</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Students</h3>
    <a href="{% url 'students:student_create' %}">Ajouter un étudiant</a>
    <br/>
    <br/>

    <form action="{% url 'students:students_list' %}" method="POST">
        {% csrf_token %}

        <label for="faculty">Classe</label>
        <select name="faculty" id="faculty">
            <option value="__all__">--</option>
            {% for faculty in all_faculties %}
                <option value="{{ faculty.pk }}"
                        {% if faculty.slug == faculty_selected.slug %}selected="selected"{% endif %}>
                    {{ faculty }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="valider">
    </form>
    <br/>

    <table border="1px" id="students_list">
        <thead>
            <tr class="table-head">
                <td>N°</td>
                <td>Nom</td>
                <td>Prénom</td>
                <td>faculté</td>
                <td>spécialité</td>
                <td>matricule</td>
            </tr>
        </thead>

        <tbody>
            {% for student in students %}
                <tr id="students_list_data">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.faculty }}</td>
                    <td>{{ student.speciality }}</td>
                    <td>{{ student.matricule }}</td>
                    <td>
                        <a href="{% url 'students:student_edit' student.pk %}">Modifier</a>
                        <a href="{% url 'students:students_details' student.pk %}">Détails</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

src/students/templates/students/student_create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    <title>students/create</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}


{% block body_content %}
    <h2>Créer un étudiant</h2>

    <form action="{% url 'students:student_create' %}" method="POST">

        {% csrf_token %}
        <p>
            {{ form.faculty.label_tag }}
            {% render_field form.faculty hx-get="/students/specialities_dropdown/" hx-target="#id_speciality" hx-trigger="change" %}
        </p>

        <p>
            {{ form.speciality.label_tag }}
            {% render_field form.speciality %}
        </p>

        <p>
            {{ form.system.label_tag }}
            {% render_field form.system hx-get="/students/level_dropdown/" hx-target="#id_level" hx-trigger="change" %}
        </p>

        <p>
            {{ form.level.label_tag }}
            {% render_field form.level %}
        </p>

        <p>
            {{ form.matricule.label_tag }}
            {% render_field form.matricule %}
        </p>
        <p>
            {{ form.first_name.label_tag }}
            {% render_field form.first_name %}
        </p>
        <p>
            {{ form.last_name.label_tag }}
            {% render_field form.last_name %}
        </p>
        <p>
            {{ form.gender.label_tag }}
            {% render_field form.gender %}
        </p>
        <p>
            {{ form.birth.label_tag }}
            {% render_field form.birth %}
        </p>

        <input type="submit" value="Enrégistrer">

    </form>

{% endblock %}

src/students/templates/students/student_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    <title>students/edit</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}


{% block body_content %}
    <h2>Modifier un étudiant</h2>

    <form action="{% url 'students:student_edit' student.pk %}" method="POST">

        {% csrf_token %}
        <p>
            {{ form.faculty.label_tag }}
            {% render_field form.faculty hx-get="/students/specialities_dropdown/" hx-target="#id_speciality" hx-trigger="change" %}
        </p>

        <p>
            {{ form.speciality.label_tag }}
            {% render_field form.speciality %}
        </p>

        <p>
            {{ form.system.label_tag }}
            {% render_field form.system hx-get="/students/level_dropdown/" hx-target="#id_level" hx-trigger="change" %}
        </p>

        <p>
            {{ form.level.label_tag }}
            {% render_field form.level %}
        </p>

        <p>
            {{ form.matricule.label_tag }}
            {% render_field form.matricule %}
        </p>
        <p>
            {{ form.first_name.label_tag }}
            {% render_field form.first_name %}
        </p>
        <p>
            {{ form.last_name.label_tag }}
            {% render_field form.last_name %}
        </p>
        <p>
            {{ form.gender.label_tag }}
            {% render_field form.gender %}
        </p>
        <p>
            {{ form.birth.label_tag }}
            {% render_field form.birth %}
        </p>

        <input type="submit" value="Modifier">

    </form>

{% endblock %}

src/students/templates/students/students_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/details</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h2>Details sur un étudient</h2>
    <div>
        <h3>Informations personnelles</h3>
        <p>Nom: {{ student.last_name }}</p>
        <p>Prénom: {{ student.first_name }}</p>
        <p>Date de naissance: {{ student.birth }}</p>
        <p>Facultée: {{ student.faculty }}</p>
        <p>Spécialitée: {{ student.speciality }}</p>
    </div>

    <div>
        <h3>Résultats</h3>
        <form action="{% url 'students:students_details' student.pk %}" method="GET">
            <select name="academic_year" id="id_academic_year"
                hx-get="{% url 'marks_and_results:semester_dropdown' %}"
                hx-trigger="change"
                hx-target="#id_semester">
                {% for academic_year in academic_years %}
                    {% if academic_year == academic_year_selected %}
                        <option value="{{ academic_year.pk }}" selected>{{ academic_year }}</option>
                    {% else %}
                        <option value="{{ academic_year.pk }}">{{ academic_year }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <select name="semester" id="id_semester">
                {% for semester in semesters %}
                    {% if semester == semester_selected %}
                        <option value="{{ semester.pk }}" selected>{{ semester }}</option>
                    {% else %}
                        <option value="{{ semester.pk }}">{{ semester }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <input type="submit" value="valider">
        </form>
        {% if not max_len %}
            <p>Aucun résultat trouvé</p>
        {% else %}
            <table border="1px">
                <thead>
                    <tr>
                        <td>Matières</td>
                        <td>Coéfficients</td>
                        <td colspan="{{ max_len }}">Notes</td>
                    </tr>
                </thead>

                {% for item in student_marks %}
                    <tr>
                        <td>{{ item.0 }}</td>
                        <td>{{ item.0.coefficient }}</td>
                        {% for mark in item.1 %}
                            <td>
                                {{ mark.mark_type }}
                                {% if mark.is_exam %} <br>
                                    <b>ex</b>
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>

{% endblock %}