src/marks_and_results/urls.py
from django.urls import path

from .views import *

app_name = "marks_and_results"

urlpatterns = [
    path('marks/', students_marks, name="students_marks"),
    path('add_marks/', add_marks, name="add_marks"),
    path('add_marks/entering/', marks_entering, name="marks_entering"),
    path('add_marks/marks_saving/', marks_saving, name="marks_saving"),
    path('edit_mark/<str:pk>/', edit_mark, name="edit_mark"),
    path('results/', results, name="results"),

    path('module_dropdown/', module_dropdown, name="module_dropdown"),
    path('lesson_dropdown/', lesson_dropdown, name="lesson_dropdown"),
    path('semester_dropdown/', semester_dropdown, name="semester_dropdown"),
]

src/sg_note/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views

from .views import index, edit_now_academic_year

urlpatterns = [
    path('', index, name='index'),
    path('edit_now_academic_year', edit_now_academic_year, name='edit_now_academic_year'),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('departs_and_mod/', include('departements_and_modules.urls')),
    path('marks_and_results/', include('marks_and_results.urls')),
    path('admin/', admin.site.urls),
]

src/departements_and_modules/models.py
import django
from django.db import models
from django.utils.text import slugify

from systems_and_levels.models import System


class AcademicYear(models.Model):
    bigin_date = models.DateField(verbose_name="Date début", default=django.utils.timezone.now)
    end_date = models.DateField(verbose_name="Date fin")
    is_now_academic_year = models.BooleanField(default=False, blank=True, verbose_name="L'actuelle année scolaire")

    def __str__(self):
        if self.bigin_date and self.end_date:
            return f"{self.bigin_date.year} - {self.end_date.year}"
        else:
            return super().__str__()

    def save(self, *args, **kwargs):
        if self.is_now_academic_year:
            now_academic_years = AcademicYear.objects.filter(is_now_academic_year=True)
            if now_academic_years:
                for i in range(len(now_academic_years)):
                    now_academic_years[i].is_now_academic_year = False
                    now_academic_years[i].save()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "année scolaire"


class Faculty(models.Model):
    name = models.CharField(max_length=200, unique=True)
    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "facultée"

    def __str__(self):
        return f"{self.name}"

    @property
    def students_count(self):
        return len(self.student_set.all())

    @property
    def modules_count(self):
        return len(self.module_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Faculty, self).save(*args, **kwargs)


class Speciality(models.Model):
    name = models.CharField(max_length=100, unique=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "spécialitée"

    def __str__(self):
        return f"{self.name}"

    @property
    def students_count(self):
        return len(self.student_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Speciality, self).save(*args, **kwargs)


class Semester(models.Model):
    semester_number = models.IntegerField()
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "semestre"

    def __str__(self):
        return f"semestre {self.semester_number}"


class Module(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name="Facultée", blank=True)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True, verbose_name="Année scolaire")
    semester = models.ForeignKey(Semester, on_delete=models.SET_NULL, null=True, verbose_name="Semestre", blank=True)
    name = models.CharField(max_length=100, verbose_name="Nom", unique=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "module"

    def __str__(self):
        return f"{self.name}"

    @property
    def lesson_count(self):
        return len(self.lesson_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Module, self).save(*args, **kwargs)


class Lesson(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name="Module")
    coefficient = models.FloatField(default=1, verbose_name="Coéfficient")
    name = models.CharField(max_length=100, verbose_name="Nom", unique=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "lesson"

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Lesson, self).save(*args, **kwargs)

src/marks_and_results/models.py
from django.db import models

# Create your models here.
from departements_and_modules.models import Lesson, Semester, AcademicYear
from students.models import Student


class Mark(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    mark_type = models.FloatField(verbose_name="Note")
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, verbose_name="Semestre", null=True)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True)
    is_exam = models.BooleanField(null=True, default=False, verbose_name="Cochez si cela est une note d'examen")

    def __str__(self):
        return f"{self.mark_type}"

    class Meta:
        verbose_name = "note"

src/marks_and_results/forms.py
from django import forms
from dynamic_forms import DynamicFormMixin, DynamicField

from departements_and_modules.models import Module, Lesson, Faculty, Semester, AcademicYear


class SearchMarks(DynamicFormMixin, forms.Form):

    def get_modules(self):
        return Module.objects.filter(faculty=self["faculty"].value())

    def get_lessons(self):
        return Lesson.objects.filter(module=self["module"].value())

    def get_semesters(self):
        return Semester.objects.filter(academic_year=self["academic_year"].value())

    faculty = forms.ModelChoiceField(
        queryset=Faculty.objects.all(),
    )

    module = DynamicField(
        forms.ModelChoiceField,
        queryset=get_modules,
    )

    lesson = DynamicField(
        forms.ModelChoiceField,
        queryset=get_lessons,
    )

    academic_year = forms.ModelChoiceField(
        queryset=AcademicYear.objects.all(),
    )

    semester = DynamicField(
        forms.ModelChoiceField,
        queryset=get_semesters,
    )


class MarkCreaterForm(DynamicFormMixin, forms.Form):
    def get_modules(self):
        return Module.objects.filter(faculty=self["faculty"].value())

    def get_lessons(self):
        return Lesson.objects.filter(module=self["module"].value())

    def get_semesters(self):
        return Semester.objects.filter(academic_year=self["academic_year"].value())

    is_exam = forms.BooleanField(label="Cochez si cela est une note d'examen", required=False)

    faculty = forms.ModelChoiceField(
        queryset=Faculty.objects.all(),
    )
    module = DynamicField(
        forms.ModelChoiceField,
        queryset=get_modules,
    )

    lesson = DynamicField(
        forms.ModelChoiceField,
        queryset=get_lessons,
    )

    academic_year = forms.ModelChoiceField(
        queryset=AcademicYear.objects.all(),
    )

    semester = DynamicField(
        forms.ModelChoiceField,
        queryset=get_semesters,
    )

src/marks_and_results/templates/marks_and_results/add_marks.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}


{% block title %}
    <title>add_marks</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}


{% block body_content %}
    <h2>Saisir des notes</h2>
    <form action="{% url 'marks_and_results:add_marks' %}" method="POST">

        {% csrf_token %}
        <p>
            {{ form.is_exam.label }}
            {% render_field form.is_exam %}
        </p>
        {% if exam_mark_already_exist %}
            <p>
                {{ exam_mark_already_exist }}
            </p>
        {% endif %}

        <p>
            {{ form.faculty.label }}
            {% render_field form.faculty hx-get="/marks_and_results/module_dropdown/" hx-trigger="change" hx-target="#id_module" %}
        </p>
        <p>
            {{ form.module.label }}
            {% render_field form.module hx-get="/marks_and_results/lesson_dropdown/" hx-trigger="change" hx-target="#id_lesson" %}
        </p>
        <p>
            {{ form.lesson.label }}
            {% render_field form.lesson %}
        </p>
        <p>
            {{ form.academic_year.label }}
            {% render_field form.academic_year hx-get="/marks_and_results/semester_dropdown/" hx-trigger="change" hx-target="#id_semester" %}
        </p>
        <p>
            {{ form.semester.label }}
            {% render_field form.semester %}
        </p>

        <p>
            <input type="submit" value="Suivant">
        </p>
    </form>

{% endblock %}

src/marks_and_results/templates/marks_and_results/edit_mark.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>edit_mark</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}


{% block body_content %}
    <h2>Modifier une note</h2>
    <form action="{% url 'marks_and_results:edit_mark' mark.pk %}" method="POST">
        {% csrf_token %}
        {{ mark.mark_type }}<br>
        <input type="number" name="mark_type" required autofocus min="0" step="any">
        <input type="submit" value="Modifier">
    </form>

{% endblock %}

src/marks_and_results/templates/marks_and_results/marks.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    <title>students/marks</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Notes des étudiants</h3>
    <h4>
        <a href="{% url 'marks_and_results:add_marks' %}">Saisir des notes</a>
    </h4>

    <h4>Rechercher</h4>
    <form action="{% url 'marks_and_results:students_marks' %}" method="GET">

        <label for="id_academic_year">Année scolaire</label>
        <select name="academic_year" id="id_academic_year"
            hx-get="{% url 'marks_and_results:semester_dropdown' %}" hx-trigger="change" hx-target="#id_semester">
            {% for academic_year in academic_years %}
                {% if academic_year == academic_year_selected %}
                    <option value="{{ academic_year.pk }}" selected> {{ academic_year }}</option>
                {% else %}
                    <option value="{{ academic_year.pk }}"> {{ academic_year }}</option>
                {% endif %}
            {% endfor %}
        </select> <br>

        <label for="id_semester">Semestre</label>
        <select name="semester" id="id_semester">
            {% for semester in semesters %}
                {% if semester == semester_selected %}
                    <option value="{{ semester.pk }}" selected> {{ semester }}</option>
                {% else %}
                    <option value="{{ semester.pk }}"> {{ semester }}</option>
                {% endif %}
            {% endfor %}
        </select> <br><br>

        <select name="faculty" id="id_faculty"
            hx-get="{% url 'marks_and_results:module_dropdown' %}" hx-trigger="change" hx-target="#id_module">
            {% for faculty in faculties %}
                {% if faculty == faculty_selected %}
                    <option value="{{ faculty.pk }}" selected> {{ faculty }}</option>
                {% else %}
                    <option value="{{ faculty.pk }}"> {{ faculty }}</option>
                {% endif %}
            {% endfor %}
        </select>

        <select name="module" id="id_module"
            hx-get="{% url 'marks_and_results:lesson_dropdown' %}" hx-trigger="change" hx-target="#id_lesson">
            {% for module in modules %}
                {% if module == module_selected %}
                    <option value="{{ module.pk }}" selected> {{ module }}</option>
                {% else %}
                    <option value="{{ module.pk }}"> {{ module }}</option>
                {% endif %}
            {% endfor %}
        </select>

        <select name="lesson" id="id_lesson">
            {% for lesson in lessons %}
                {% if lesson == lesson_selected %}
                    <option value="{{ lesson.pk }}" selected> {{ lesson }}</option>
                {% else %}
                    <option value="{{ lesson.pk }}"> {{ lesson }}</option>
                {% endif %}
            {% endfor %}
        </select>

        <input type="submit" value="valider">
    </form>
    <br>
    <br>

    {% if max_len %}
        <p>
            <a href="{% url 'marks_and_results:results' %}">Afficher les résultats</a>
        </p>
        <table border=".5px" id="students_marks">
            <thead>
                <tr>
                    <td>N°</td>
                    <td>Nom et prénom</td>
                    <td colspan="{{max_len}}">Notes de classe</td>
                </tr>
            </thead>
            <tbody>
                {% for mark in marks %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ mark.student }} </td>
                        {% for m in mark.marks %}
                            <td>
                                {{ m.mark_type }} <br>
                                {% if m.is_exam %}
                                    ex <br>
                                {% endif %}
                                <a href="{% url 'marks_and_results:edit_mark' m.pk %}">modifier</a>
                            </td>

                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}

        <p>Aucune note trouvé</p>

    {% endif %}

{% endblock %}

src/marks_and_results/templates/marks_and_results/marks_entering.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}


{% block title %}
    <title>add_marks/entering</title>
<link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}


{% block body_content %}
    <h2>Saisir des notes</h2>
    <div>
        <p>{{ academic_year_selected }} | {{ semester_selected }}</p>
        <p>Facultée: {{ faculty_selected }}</p>
        <p>Module: {{ module_selected }}</p>
        <p>Matière: {{ lesson_selected }}</p>
    </div>
    <p>ATTENTION: Les champs laissés vides seront remplacé par un 0 (zéro)</p>
    <form action="{% url 'marks_and_results:marks_saving' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
            {{ field.as_hidden }}
        {% endfor %}

        <table border="1px">
            <tr>
                <td>Etudiant</td>
                <td>Matricule</td>
                <td>Note</td>
            </tr>
            {% for student in students %}
                <tr>
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.pk }}</td>
                    <td><input type="number" step="any" min="0" name="{{student.pk}}_mark"></td>
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Enrégistrer">
    </form>

{% endblock %}

src/marks_and_results/templates/marks_and_results/results.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    <title>students/marks</title>
<link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Résultats</h3>
    <div>
        <table cellspacing="10px">
            <thead>
                <tr>
                    <td><b><i>Facultté</i></b></td>
                    <td><b><i>Module</i></b></td>
                    <td><b><i>Matière</i></b></td>
                    <td><b><i>Année scolaire</i></b></td>
                    <td><b><i>Semestre</i></b></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ faculty_selected }}</td>
                    <td>{{ module_selected }}</td>
                    <td>{{ lesson_selected }}</td>
                    <td>{{ academic_year_selected }}</td>
                    <td>{{ semester_selected }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    {% if student_results %}
        <table border=".5px" id="students_marks">
            <thead>
                <tr>
                    <td>N°</td>
                    <td>Nom et prénom</td>
                    <td>Moyenne de classe</td>
                    <td>Note d'examen</td>
                    <td>Moyenne semestrielle</td>
                    <td>Moyenne generale semestrielle</td>
                    <td>Moyenne annuelle</td>
                </tr>
            </thead>
            <tbody>
                {% for result in student_results %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ result.student.full_name }}</td>
                        <td>{{ result.lesson_class_mean|floatformat:2 }}</td>
                        <td>{{ result.lesson_exam_mark }}</td>
                        <td>{{ result.lesson_semester_mean|floatformat:2 }}</td>
                        <td>{{ result.semester_mean }}</td>
                        <td>{{ result.annual_mean }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun resultat disponible</p>
    {% endif %}

{% endblock %}