src/departements_and_modules/urls.py
from django.urls import path

from .views import *

app_name = "departements_and_modules"

urlpatterns = [
    path('faculties/', students_faculties, name="students_faculties"),
    path('create_faculties/', create_faculties, name="create_faculties"),

    path('modules/', students_modules, name="students_modules"),
    path('create_modules/', create_modules, name="create_modules"),

    path('lessons/', students_lessons, name="students_lessons"),
    path('create_lessons/', create_lessons, name="create_lessons"),

    path('specialities/', students_specialities, name="students_specialities"),
    path('create_specialities/', create_specialities, name="create_specialities"),
]

src/sg_note/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views

from .views import index, edit_now_academic_year

urlpatterns = [
    path('', index, name='index'),
    path('edit_now_academic_year', edit_now_academic_year, name='edit_now_academic_year'),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('departs_and_mod/', include('departements_and_modules.urls')),
    path('marks_and_results/', include('marks_and_results.urls')),
    path('admin/', admin.site.urls),
]

src/departements_and_modules/models.py
import django
from django.db import models
from django.utils.text import slugify

from systems_and_levels.models import System


class AcademicYear(models.Model):
    bigin_date = models.DateField(verbose_name="Date début", default=django.utils.timezone.now)
    end_date = models.DateField(verbose_name="Date fin")
    is_now_academic_year = models.BooleanField(default=False, blank=True, verbose_name="L'actuelle année scolaire")

    def __str__(self):
        if self.bigin_date and self.end_date:
            return f"{self.bigin_date.year} - {self.end_date.year}"
        else:
            return super().__str__()

    def save(self, *args, **kwargs):
        if self.is_now_academic_year:
            now_academic_years = AcademicYear.objects.filter(is_now_academic_year=True)
            if now_academic_years:
                for i in range(len(now_academic_years)):
                    now_academic_years[i].is_now_academic_year = False
                    now_academic_years[i].save()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "année scolaire"


class Faculty(models.Model):
    name = models.CharField(max_length=200, unique=True)
    system = models.ForeignKey(System, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "facultée"

    def __str__(self):
        return f"{self.name}"

    @property
    def students_count(self):
        return len(self.student_set.all())

    @property
    def modules_count(self):
        return len(self.module_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Faculty, self).save(*args, **kwargs)


class Speciality(models.Model):
    name = models.CharField(max_length=100, unique=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "spécialitée"

    def __str__(self):
        return f"{self.name}"

    @property
    def students_count(self):
        return len(self.student_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Speciality, self).save(*args, **kwargs)


class Semester(models.Model):
    semester_number = models.IntegerField()
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = "semestre"

    def __str__(self):
        return f"semestre {self.semester_number}"


class Module(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name="Facultée", blank=True)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, null=True, verbose_name="Année scolaire")
    semester = models.ForeignKey(Semester, on_delete=models.SET_NULL, null=True, verbose_name="Semestre", blank=True)
    name = models.CharField(max_length=100, verbose_name="Nom", unique=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "module"

    def __str__(self):
        return f"{self.name}"

    @property
    def lesson_count(self):
        return len(self.lesson_set.all())

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Module, self).save(*args, **kwargs)


class Lesson(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name="Module")
    coefficient = models.FloatField(default=1, verbose_name="Coéfficient")
    name = models.CharField(max_length=100, verbose_name="Nom", unique=True)
    slug = models.SlugField(max_length=130, blank=True, null=True)

    class Meta:
        verbose_name = "lesson"

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Lesson, self).save(*args, **kwargs)

src/departements_and_modules/forms.py
from django import forms
from dynamic_forms import DynamicField, DynamicFormMixin

from departements_and_modules.models import Faculty, Module, Speciality, Lesson, Semester, AcademicYear


class ModuleCreateForm(DynamicFormMixin, forms.Form):

    def get_semester(self):
        return Semester.objects.filter(academic_year=self["academic_year"].value())

    name = forms.CharField(max_length=100, label="Nom")
    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all())
    academic_year = forms.ModelChoiceField(queryset=AcademicYear.objects.all())
    semester = DynamicField(forms.ModelChoiceField, queryset=get_semester)


class FacultyCreateForm(forms.ModelForm):

    class Meta:
        model = Faculty
        fields = (
            "name",
            "system",
        )


class SpecilityCreateForm(forms.ModelForm):

    class Meta:
        model = Speciality
        fields = (
            "name",
            "faculty",
        )


class LessonCreateForm(forms.ModelForm):

    class Meta:
        model = Lesson
        fields = (
            "name",
            "coefficient",
            "module",
        )

src/departements_and_modules/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import ModuleCreateForm, FacultyCreateForm, SpecilityCreateForm, LessonCreateForm
from .models import Faculty, Module, Lesson, Speciality, AcademicYear


@login_required()
def students_faculties(request):
    context = {
        "faculties": Faculty.objects.all(),
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True)
    }
    return render(request, "departements_and_modules/faculties.html", context=context)


@login_required()
def students_modules(request):
    context = {
        "modules": Module.objects.all(),
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True)
    }
    return render(request, "departements_and_modules/modules.html", context=context)


@login_required()
def students_lessons(request):
    context = {
        "lessons": Lesson.objects.all(),
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True)
    }
    return render(request, "departements_and_modules/lessons.html", context=context)


@login_required()
def students_specialities(request):
    context = {
        "specialities": Speciality.objects.all(),
        "now_academic_year": AcademicYear.objects.get(is_now_academic_year=True)
    }
    return render(request, "departements_and_modules/specialities.html", context=context)


# ---------- Create views ---------------------

@login_required()
def create_faculties(request):
    context = {}
    if request.method == "POST":
        form = FacultyCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            faculty = Faculty()
            faculty.name = data.get("name")
            faculty.system = data.get("system")

            faculty.save()
            return redirect("departements_and_modules:students_faculties")
    else:
        form = FacultyCreateForm()

    context["form"] = form
    return render(request,  "departements_and_modules/create_faculties.html", context=context)


@login_required()
def create_specialities(request):
    context = {}
    if request.method == "POST":
        form = SpecilityCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            speciality = Speciality()
            speciality.name = data.get("name")
            speciality.faculty = data.get("faculty")

            speciality.save()
            return redirect("departements_and_modules:students_specialities")
    else:
        form = SpecilityCreateForm()

    context["form"] = form
    return render(request,  "departements_and_modules/create_specialities.html", context=context)


@login_required()
def create_modules(request):
    context = {}
    if request.method == "POST":
        form = ModuleCreateForm(request.POST)
        if form.is_valid():
            datas = form.cleaned_data
            module = Module()
            module.name = datas.get("name")
            module.faculty = datas.get("faculty")
            module.academic_year = datas.get("academic_year")
            module.semester = datas.get("semester")

            module.save()
            return redirect("departements_and_modules:students_modules")
    else:
        form = ModuleCreateForm()

    context['form'] = form
    return render(request, "departements_and_modules/create_modules.html", context=context)


@login_required()
def create_lessons(request):
    context = {}
    if request.method == "POST":
        form = LessonCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            lesson = Lesson()
            lesson.name = data.get("name")
            lesson.coefficient = data.get("coefficient")
            lesson.module = data.get("module")

            lesson.save()
            return redirect("departements_and_modules:students_lessons")
    else:
        form = LessonCreateForm()

    context["form"] = form
    return render(request,  "departements_and_modules/create_lessons.html", context=context)

src/departements_and_modules/templates/departements_and_modules/create_faculties.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create module</title>
<!--    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>-->
</head>
<body>
    <h2>Ajouter une nouvelle facultée</h2>
    <form action="{% url 'departements_and_modules:create_faculties' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Enrégistrer">
    </form>

</body>
</html>

src/departements_and_modules/templates/departements_and_modules/create_lessons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create module</title>
<!--    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>-->
</head>
<body>
    <h2>Ajouter une nouvelle matière</h2>
    <form action="{% url 'departements_and_modules:create_lessons' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Enrégistrer">
    </form>
</body>
</html>

src/departements_and_modules/templates/departements_and_modules/create_modules.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create module</title>
    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>
</head>
<body>
    <h2>Ajouter un nouveau modules</h2>
    <form action="{% url 'departements_and_modules:create_modules' %}" method="POST">
        {% csrf_token %}
        <p>
            {{ form.name.label_tag }}
            {% render_field form.name %}
        </p>
        <p>
            {{ form.faculty.label_tag }}
            {% render_field form.faculty %}
        </p>

        <p>
            {{ form.academic_year.label_tag }}
            {% render_field form.academic_year hx-get="/marks_and_results/semester_dropdown/" hx-target="#id_semester" hx-trigger="change"%}
        </p>

        <p>
            {{ form.semester.label_tag }}
            {% render_field form.semester %}
        </p>

        <input type="submit" value="Enrégistrer">
    </form>

</body>
</html>

src/departements_and_modules/templates/departements_and_modules/create_specialities.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create module</title>
<!--    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>-->
</head>
<body>
    <h2>Ajouter une nouvelle spécialitée</h2>
    <form action="{% url 'departements_and_modules:create_specialities' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Enrégistrer">
    </form>

</body>
</html>

src/departements_and_modules/templates/departements_and_modules/faculties.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/faculty</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Facultés</h3>

    <h4><a href="{% url 'departements_and_modules:create_faculties' %}">Ajoutez une faculté </a></h4>

    <table border="1px">
        <tr class="table-head">
                <td>Nom de la facultée</td>
                <td>Nombre de module</td>
                <td>Nombre d'étudiant</td>
        </tr>
        {% for faculty in faculties %}
        <tr>
            <td>{{ faculty.name }}</td>
            <td>{{ faculty.modules_count }}</td>
            <td>{{ faculty.students_count }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

src/departements_and_modules/templates/departements_and_modules/lessons.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/lessons</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Matières</h3>

    <h4><a href="{% url 'departements_and_modules:create_lessons' %}">Ajoutez une matière</a></h4>

    <table border="1px">
        <tr class="table-head">
            <td>Nom de la matière</td>
            <td>coéfficient</td>
            <td>Module d'appartenance</td>
        </tr>
        {% for lesson in lessons %}
        <tr>
            <td>{{ lesson.name }}</td>
            <td>{{ lesson.coefficient }}</td>
            <td>{{ lesson.module }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

src/departements_and_modules/templates/departements_and_modules/modules.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/modules</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Modules</h3>

    <h4><a href="{% url 'departements_and_modules:create_modules' %}">Ajoutez un module</a> </h4>

    <table border="1px">
        <tr class="table-head">
            <td>Nom du module</td>
            <td>Nombre de matière</td>
            <td>faculté d'appartenance</td>
        </tr>
        {% for module in modules %}
        <tr>
            <td>{{ module.name }}</td>
            <td>{{ module.lesson_count }}</td>
            <td>{{ module.faculty }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

src/departements_and_modules/templates/departements_and_modules/specialities.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>students/specialités</title>
    <link rel="stylesheet" href="{% static 'sg_note/css/home-style.css' %}">
{% endblock %}

{% block now_academic_year %}
    <b>{{ now_academic_year }}</b> <a href="{% url 'edit_now_academic_year' %}">modifier</a>
{% endblock %}

{% block body_content %}
    <h3>Specialités</h3>
    <h4>
        <a href="{% url 'departements_and_modules:create_specialities' %}">Ajoutez une spécialité</a>
    </h4>

    <table border="1px">
        <tr class="table-head">
            <td>Nom de la spécialité</td>
            <td>faculté d'appartenance</td>
            <td>Nombre d'étudiant</td>
        </tr>
        {% for speciality in specialities %}
        <tr>
            <td>{{ speciality.name }}</td>
            <td>{{ speciality.faculty }}</td>
            <td>{{ speciality.students_count }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}